// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/cmd.proto

#ifndef PROTOBUF_common_2fcmd_2eproto__INCLUDED
#define PROTOBUF_common_2fcmd_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto_messages {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2fcmd_2eproto();
void protobuf_AssignDesc_common_2fcmd_2eproto();
void protobuf_ShutdownFile_common_2fcmd_2eproto();

class CMD;

// ===================================================================

class CMD : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto_messages.CMD) */ {
 public:
  CMD();
  virtual ~CMD();

  CMD(const CMD& from);

  inline CMD& operator=(const CMD& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMD& default_instance();

  void Swap(CMD* other);

  // implements Message ----------------------------------------------

  inline CMD* New() const { return New(NULL); }

  CMD* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMD& from);
  void MergeFrom(const CMD& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMD* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool CAMERA0_ON = 1;
  void clear_camera0_on();
  static const int kCAMERA0ONFieldNumber = 1;
  bool camera0_on() const;
  void set_camera0_on(bool value);

  // optional bool CAMERA1_ON = 2;
  void clear_camera1_on();
  static const int kCAMERA1ONFieldNumber = 2;
  bool camera1_on() const;
  void set_camera1_on(bool value);

  // optional bool CAMERA2_ON = 3;
  void clear_camera2_on();
  static const int kCAMERA2ONFieldNumber = 3;
  bool camera2_on() const;
  void set_camera2_on(bool value);

  // optional bool CAMERA3_ON = 4;
  void clear_camera3_on();
  static const int kCAMERA3ONFieldNumber = 4;
  bool camera3_on() const;
  void set_camera3_on(bool value);

  // optional bool CAMERA4_ON = 5;
  void clear_camera4_on();
  static const int kCAMERA4ONFieldNumber = 5;
  bool camera4_on() const;
  void set_camera4_on(bool value);

  // optional bool CAMERA5_ON = 6;
  void clear_camera5_on();
  static const int kCAMERA5ONFieldNumber = 6;
  bool camera5_on() const;
  void set_camera5_on(bool value);

  // optional bool CAMERA6_ON = 7;
  void clear_camera6_on();
  static const int kCAMERA6ONFieldNumber = 7;
  bool camera6_on() const;
  void set_camera6_on(bool value);

  // optional bool CAMERA7_ON = 8;
  void clear_camera7_on();
  static const int kCAMERA7ONFieldNumber = 8;
  bool camera7_on() const;
  void set_camera7_on(bool value);

  // @@protoc_insertion_point(class_scope:proto_messages.CMD)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  bool camera0_on_;
  bool camera1_on_;
  bool camera2_on_;
  bool camera3_on_;
  bool camera4_on_;
  bool camera5_on_;
  bool camera6_on_;
  bool camera7_on_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_common_2fcmd_2eproto();
  friend void protobuf_AssignDesc_common_2fcmd_2eproto();
  friend void protobuf_ShutdownFile_common_2fcmd_2eproto();

  void InitAsDefaultInstance();
  static CMD* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMD

// optional bool CAMERA0_ON = 1;
inline void CMD::clear_camera0_on() {
  camera0_on_ = false;
}
inline bool CMD::camera0_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA0_ON)
  return camera0_on_;
}
inline void CMD::set_camera0_on(bool value) {
  
  camera0_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA0_ON)
}

// optional bool CAMERA1_ON = 2;
inline void CMD::clear_camera1_on() {
  camera1_on_ = false;
}
inline bool CMD::camera1_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA1_ON)
  return camera1_on_;
}
inline void CMD::set_camera1_on(bool value) {
  
  camera1_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA1_ON)
}

// optional bool CAMERA2_ON = 3;
inline void CMD::clear_camera2_on() {
  camera2_on_ = false;
}
inline bool CMD::camera2_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA2_ON)
  return camera2_on_;
}
inline void CMD::set_camera2_on(bool value) {
  
  camera2_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA2_ON)
}

// optional bool CAMERA3_ON = 4;
inline void CMD::clear_camera3_on() {
  camera3_on_ = false;
}
inline bool CMD::camera3_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA3_ON)
  return camera3_on_;
}
inline void CMD::set_camera3_on(bool value) {
  
  camera3_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA3_ON)
}

// optional bool CAMERA4_ON = 5;
inline void CMD::clear_camera4_on() {
  camera4_on_ = false;
}
inline bool CMD::camera4_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA4_ON)
  return camera4_on_;
}
inline void CMD::set_camera4_on(bool value) {
  
  camera4_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA4_ON)
}

// optional bool CAMERA5_ON = 6;
inline void CMD::clear_camera5_on() {
  camera5_on_ = false;
}
inline bool CMD::camera5_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA5_ON)
  return camera5_on_;
}
inline void CMD::set_camera5_on(bool value) {
  
  camera5_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA5_ON)
}

// optional bool CAMERA6_ON = 7;
inline void CMD::clear_camera6_on() {
  camera6_on_ = false;
}
inline bool CMD::camera6_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA6_ON)
  return camera6_on_;
}
inline void CMD::set_camera6_on(bool value) {
  
  camera6_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA6_ON)
}

// optional bool CAMERA7_ON = 8;
inline void CMD::clear_camera7_on() {
  camera7_on_ = false;
}
inline bool CMD::camera7_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA7_ON)
  return camera7_on_;
}
inline void CMD::set_camera7_on(bool value) {
  
  camera7_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA7_ON)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_messages

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2fcmd_2eproto__INCLUDED
