// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/cmd.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common/cmd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto_messages {

namespace {

const ::google::protobuf::Descriptor* CMD_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMD_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_common_2fcmd_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_common_2fcmd_2eproto() {
  protobuf_AddDesc_common_2fcmd_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "common/cmd.proto");
  GOOGLE_CHECK(file != NULL);
  CMD_descriptor_ = file->message_type(0);
  static const int CMD_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera0_on_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera1_on_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera2_on_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera3_on_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera4_on_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera5_on_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera6_on_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, camera7_on_),
  };
  CMD_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CMD_descriptor_,
      CMD::default_instance_,
      CMD_offsets_,
      -1,
      -1,
      -1,
      sizeof(CMD),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMD, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_common_2fcmd_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CMD_descriptor_, &CMD::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_common_2fcmd_2eproto() {
  delete CMD::default_instance_;
  delete CMD_reflection_;
}

void protobuf_AddDesc_common_2fcmd_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_common_2fcmd_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020common/cmd.proto\022\016proto_messages\"\245\001\n\003C"
    "MD\022\022\n\nCAMERA0_ON\030\001 \001(\010\022\022\n\nCAMERA1_ON\030\002 \001"
    "(\010\022\022\n\nCAMERA2_ON\030\003 \001(\010\022\022\n\nCAMERA3_ON\030\004 \001"
    "(\010\022\022\n\nCAMERA4_ON\030\005 \001(\010\022\022\n\nCAMERA5_ON\030\006 \001"
    "(\010\022\022\n\nCAMERA6_ON\030\007 \001(\010\022\022\n\nCAMERA7_ON\030\010 \001"
    "(\010b\006proto3", 210);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common/cmd.proto", &protobuf_RegisterTypes);
  CMD::default_instance_ = new CMD();
  CMD::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_common_2fcmd_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_common_2fcmd_2eproto {
  StaticDescriptorInitializer_common_2fcmd_2eproto() {
    protobuf_AddDesc_common_2fcmd_2eproto();
  }
} static_descriptor_initializer_common_2fcmd_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CMD::kCAMERA0ONFieldNumber;
const int CMD::kCAMERA1ONFieldNumber;
const int CMD::kCAMERA2ONFieldNumber;
const int CMD::kCAMERA3ONFieldNumber;
const int CMD::kCAMERA4ONFieldNumber;
const int CMD::kCAMERA5ONFieldNumber;
const int CMD::kCAMERA6ONFieldNumber;
const int CMD::kCAMERA7ONFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CMD::CMD()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto_messages.CMD)
}

void CMD::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CMD::CMD(const CMD& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:proto_messages.CMD)
}

void CMD::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  camera0_on_ = false;
  camera1_on_ = false;
  camera2_on_ = false;
  camera3_on_ = false;
  camera4_on_ = false;
  camera5_on_ = false;
  camera6_on_ = false;
  camera7_on_ = false;
}

CMD::~CMD() {
  // @@protoc_insertion_point(destructor:proto_messages.CMD)
  SharedDtor();
}

void CMD::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CMD::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMD::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMD_descriptor_;
}

const CMD& CMD::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2fcmd_2eproto();
  return *default_instance_;
}

CMD* CMD::default_instance_ = NULL;

CMD* CMD::New(::google::protobuf::Arena* arena) const {
  CMD* n = new CMD;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CMD::Clear() {
// @@protoc_insertion_point(message_clear_start:proto_messages.CMD)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(CMD, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CMD*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(camera0_on_, camera7_on_);

#undef ZR_HELPER_
#undef ZR_

}

bool CMD::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto_messages.CMD)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool CAMERA0_ON = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera0_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_CAMERA1_ON;
        break;
      }

      // optional bool CAMERA1_ON = 2;
      case 2: {
        if (tag == 16) {
         parse_CAMERA1_ON:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera1_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_CAMERA2_ON;
        break;
      }

      // optional bool CAMERA2_ON = 3;
      case 3: {
        if (tag == 24) {
         parse_CAMERA2_ON:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera2_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_CAMERA3_ON;
        break;
      }

      // optional bool CAMERA3_ON = 4;
      case 4: {
        if (tag == 32) {
         parse_CAMERA3_ON:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera3_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_CAMERA4_ON;
        break;
      }

      // optional bool CAMERA4_ON = 5;
      case 5: {
        if (tag == 40) {
         parse_CAMERA4_ON:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera4_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_CAMERA5_ON;
        break;
      }

      // optional bool CAMERA5_ON = 6;
      case 6: {
        if (tag == 48) {
         parse_CAMERA5_ON:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera5_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_CAMERA6_ON;
        break;
      }

      // optional bool CAMERA6_ON = 7;
      case 7: {
        if (tag == 56) {
         parse_CAMERA6_ON:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera6_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_CAMERA7_ON;
        break;
      }

      // optional bool CAMERA7_ON = 8;
      case 8: {
        if (tag == 64) {
         parse_CAMERA7_ON:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &camera7_on_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto_messages.CMD)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto_messages.CMD)
  return false;
#undef DO_
}

void CMD::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto_messages.CMD)
  // optional bool CAMERA0_ON = 1;
  if (this->camera0_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->camera0_on(), output);
  }

  // optional bool CAMERA1_ON = 2;
  if (this->camera1_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->camera1_on(), output);
  }

  // optional bool CAMERA2_ON = 3;
  if (this->camera2_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->camera2_on(), output);
  }

  // optional bool CAMERA3_ON = 4;
  if (this->camera3_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->camera3_on(), output);
  }

  // optional bool CAMERA4_ON = 5;
  if (this->camera4_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->camera4_on(), output);
  }

  // optional bool CAMERA5_ON = 6;
  if (this->camera5_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->camera5_on(), output);
  }

  // optional bool CAMERA6_ON = 7;
  if (this->camera6_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->camera6_on(), output);
  }

  // optional bool CAMERA7_ON = 8;
  if (this->camera7_on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->camera7_on(), output);
  }

  // @@protoc_insertion_point(serialize_end:proto_messages.CMD)
}

::google::protobuf::uint8* CMD::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto_messages.CMD)
  // optional bool CAMERA0_ON = 1;
  if (this->camera0_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->camera0_on(), target);
  }

  // optional bool CAMERA1_ON = 2;
  if (this->camera1_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->camera1_on(), target);
  }

  // optional bool CAMERA2_ON = 3;
  if (this->camera2_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->camera2_on(), target);
  }

  // optional bool CAMERA3_ON = 4;
  if (this->camera3_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->camera3_on(), target);
  }

  // optional bool CAMERA4_ON = 5;
  if (this->camera4_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->camera4_on(), target);
  }

  // optional bool CAMERA5_ON = 6;
  if (this->camera5_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->camera5_on(), target);
  }

  // optional bool CAMERA6_ON = 7;
  if (this->camera6_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->camera6_on(), target);
  }

  // optional bool CAMERA7_ON = 8;
  if (this->camera7_on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->camera7_on(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:proto_messages.CMD)
  return target;
}

int CMD::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:proto_messages.CMD)
  int total_size = 0;

  // optional bool CAMERA0_ON = 1;
  if (this->camera0_on() != 0) {
    total_size += 1 + 1;
  }

  // optional bool CAMERA1_ON = 2;
  if (this->camera1_on() != 0) {
    total_size += 1 + 1;
  }

  // optional bool CAMERA2_ON = 3;
  if (this->camera2_on() != 0) {
    total_size += 1 + 1;
  }

  // optional bool CAMERA3_ON = 4;
  if (this->camera3_on() != 0) {
    total_size += 1 + 1;
  }

  // optional bool CAMERA4_ON = 5;
  if (this->camera4_on() != 0) {
    total_size += 1 + 1;
  }

  // optional bool CAMERA5_ON = 6;
  if (this->camera5_on() != 0) {
    total_size += 1 + 1;
  }

  // optional bool CAMERA6_ON = 7;
  if (this->camera6_on() != 0) {
    total_size += 1 + 1;
  }

  // optional bool CAMERA7_ON = 8;
  if (this->camera7_on() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMD::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto_messages.CMD)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CMD* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CMD>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto_messages.CMD)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto_messages.CMD)
    MergeFrom(*source);
  }
}

void CMD::MergeFrom(const CMD& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto_messages.CMD)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.camera0_on() != 0) {
    set_camera0_on(from.camera0_on());
  }
  if (from.camera1_on() != 0) {
    set_camera1_on(from.camera1_on());
  }
  if (from.camera2_on() != 0) {
    set_camera2_on(from.camera2_on());
  }
  if (from.camera3_on() != 0) {
    set_camera3_on(from.camera3_on());
  }
  if (from.camera4_on() != 0) {
    set_camera4_on(from.camera4_on());
  }
  if (from.camera5_on() != 0) {
    set_camera5_on(from.camera5_on());
  }
  if (from.camera6_on() != 0) {
    set_camera6_on(from.camera6_on());
  }
  if (from.camera7_on() != 0) {
    set_camera7_on(from.camera7_on());
  }
}

void CMD::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto_messages.CMD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMD::CopyFrom(const CMD& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto_messages.CMD)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMD::IsInitialized() const {

  return true;
}

void CMD::Swap(CMD* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CMD::InternalSwap(CMD* other) {
  std::swap(camera0_on_, other->camera0_on_);
  std::swap(camera1_on_, other->camera1_on_);
  std::swap(camera2_on_, other->camera2_on_);
  std::swap(camera3_on_, other->camera3_on_);
  std::swap(camera4_on_, other->camera4_on_);
  std::swap(camera5_on_, other->camera5_on_);
  std::swap(camera6_on_, other->camera6_on_);
  std::swap(camera7_on_, other->camera7_on_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CMD::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMD_descriptor_;
  metadata.reflection = CMD_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CMD

// optional bool CAMERA0_ON = 1;
void CMD::clear_camera0_on() {
  camera0_on_ = false;
}
 bool CMD::camera0_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA0_ON)
  return camera0_on_;
}
 void CMD::set_camera0_on(bool value) {
  
  camera0_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA0_ON)
}

// optional bool CAMERA1_ON = 2;
void CMD::clear_camera1_on() {
  camera1_on_ = false;
}
 bool CMD::camera1_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA1_ON)
  return camera1_on_;
}
 void CMD::set_camera1_on(bool value) {
  
  camera1_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA1_ON)
}

// optional bool CAMERA2_ON = 3;
void CMD::clear_camera2_on() {
  camera2_on_ = false;
}
 bool CMD::camera2_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA2_ON)
  return camera2_on_;
}
 void CMD::set_camera2_on(bool value) {
  
  camera2_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA2_ON)
}

// optional bool CAMERA3_ON = 4;
void CMD::clear_camera3_on() {
  camera3_on_ = false;
}
 bool CMD::camera3_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA3_ON)
  return camera3_on_;
}
 void CMD::set_camera3_on(bool value) {
  
  camera3_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA3_ON)
}

// optional bool CAMERA4_ON = 5;
void CMD::clear_camera4_on() {
  camera4_on_ = false;
}
 bool CMD::camera4_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA4_ON)
  return camera4_on_;
}
 void CMD::set_camera4_on(bool value) {
  
  camera4_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA4_ON)
}

// optional bool CAMERA5_ON = 6;
void CMD::clear_camera5_on() {
  camera5_on_ = false;
}
 bool CMD::camera5_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA5_ON)
  return camera5_on_;
}
 void CMD::set_camera5_on(bool value) {
  
  camera5_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA5_ON)
}

// optional bool CAMERA6_ON = 7;
void CMD::clear_camera6_on() {
  camera6_on_ = false;
}
 bool CMD::camera6_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA6_ON)
  return camera6_on_;
}
 void CMD::set_camera6_on(bool value) {
  
  camera6_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA6_ON)
}

// optional bool CAMERA7_ON = 8;
void CMD::clear_camera7_on() {
  camera7_on_ = false;
}
 bool CMD::camera7_on() const {
  // @@protoc_insertion_point(field_get:proto_messages.CMD.CAMERA7_ON)
  return camera7_on_;
}
 void CMD::set_camera7_on(bool value) {
  
  camera7_on_ = value;
  // @@protoc_insertion_point(field_set:proto_messages.CMD.CAMERA7_ON)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto_messages

// @@protoc_insertion_point(global_scope)
